replicaCount: 3

ingress:
  hosts:
    - host: "hello.example.com"
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
