name: CD

on:
  workflow_run:
    workflows:
      - Terraform
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name eks-production-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/