name: CI

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ci:
    name: CI Pipeline

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: |
          helm lint helm/apps/hello-app \
            --values helm/apps/hello-app/values.yaml \
            --values helm/apps/hello-app/values-dev.yml

      - name: Docker Build Test
        run: |
          docker build --file docker/Dockerfile --tag hello-app:test .
